-- ============================================================
-- PikTag foreign-key audit
-- AUTO-GENERATED by scripts/gen_migration_drift_check.py
--
-- Dumps EVERY foreign key in schema public with its ON DELETE /
-- ON UPDATE rule. NOT derived from migrations — base-schema FKs
-- aren't in any migration file, which is exactly why the
-- "can't delete a Vibe" bug (2026-05) went undetected: the
-- object-existence drift check structurally cannot see a wrong
-- delete-rule on an FK no migration declares.
--
-- HOW TO READ: rows are ordered dangerous-first. An FK with
-- delete_rule = 'NO ACTION' or 'RESTRICT' BLOCKS deletion of the
-- referenced row while any child row points at it. That is a
-- latent "X can't be deleted" bug IFF there's a user-facing
-- delete path for the referenced table. For each such row ask:
--   "Can a user delete a <referenced_table> row in the app?"
--   If yes and the child rows shouldn't block it → the FK should
--   be ON DELETE SET NULL (keep child, drop the link) or CASCADE
--   (child is owned by parent). See migration
--   20260516000000_scan_session_fk_set_null.sql for the pattern.
-- ============================================================
SELECT
  con.conrelid::regclass::text  AS referencing_table,
  att.attname                   AS referencing_column,
  con.confrelid::regclass::text AS referenced_table,
  con.conname                   AS constraint_name,
  CASE con.confdeltype
    WHEN 'a' THEN 'NO ACTION'
    WHEN 'r' THEN 'RESTRICT'
    WHEN 'c' THEN 'CASCADE'
    WHEN 'n' THEN 'SET NULL'
    WHEN 'd' THEN 'SET DEFAULT'
  END AS on_delete,
  CASE con.confupdtype
    WHEN 'a' THEN 'NO ACTION'
    WHEN 'r' THEN 'RESTRICT'
    WHEN 'c' THEN 'CASCADE'
    WHEN 'n' THEN 'SET NULL'
    WHEN 'd' THEN 'SET DEFAULT'
  END AS on_update,
  -- Dangerous = blocks parent delete. Surfaced first.
  (con.confdeltype IN ('a','r')) AS blocks_parent_delete
FROM pg_constraint con
JOIN pg_class      rel ON rel.oid = con.conrelid
JOIN pg_namespace  ns  ON ns.oid  = rel.relnamespace
JOIN pg_attribute  att ON att.attrelid = con.conrelid
                      AND att.attnum   = ANY (con.conkey)
WHERE con.contype = 'f'
  AND ns.nspname  = 'public'
ORDER BY blocks_parent_delete DESC,
         referenced_table,
         referencing_table;
