#!/usr/bin/env python3
"""
Regenerates the DB drift-check SQL artifacts from the migration files.

Run after adding/changing migrations:

    python3 mobile/scripts/gen_migration_drift_check.py

Emits two files into mobile/scripts/:

  1. migration_drift_check.sql
     One query. For every object DECLARED in a migration
     (function / policy / trigger / table / added column / cron job
     / index) it reports present=true|false against the live DB.
     present=false ⇒ that migration was never (fully) applied.

  2. fk_audit.sql
     One query. Dumps EVERY foreign key in schema public with its
     ON DELETE / ON UPDATE rule, dangerous ones first. This is NOT
     derived from migrations (base-schema FKs aren't in any
     migration file) — it's a full catalog dump for human review.
     Rationale: the "can't delete a Vibe" bug (2026-05) was a
     base-schema FK with ON DELETE NO ACTION. The object-existence
     check structurally cannot catch a wrong-delete-rule on an FK
     that no migration declares. This audit makes that bug class
     visible: any FK with delete_rule NO ACTION/RESTRICT that sits
     under a user-facing delete path is a latent failure.

Note: this project applies migrations MANUALLY via the Supabase
SQL Editor (not `supabase db push`), so schema_migrations doesn't
reflect reality — hence the need to audit drift by inspecting the
live catalog.
"""

import re
from collections import Counter
from pathlib import Path

MIG_DIR = Path(__file__).resolve().parent.parent / "supabase" / "migrations"
OUT_DIR = Path(__file__).resolve().parent

# Strip line comments before matching so a `-- CREATE INDEX ...`
# explanatory comment doesn't get picked up as a real declaration.
def strip_sql_comments(txt: str) -> str:
    out = []
    for line in txt.splitlines():
        # naive but sufficient: drop everything from the first `--`
        # that isn't inside a string literal. Migrations here don't
        # put `--` inside string literals, so the naive cut is safe.
        idx = line.find("--")
        out.append(line if idx == -1 else line[:idx])
    return "\n".join(out)


RE_FUNC = re.compile(
    r"CREATE\s+(?:OR\s+REPLACE\s+)?FUNCTION\s+(?:public\.)?(\w+)\s*\(", re.I
)
RE_POLICY = re.compile(
    r'CREATE\s+POLICY\s+"([^"]+)"\s+ON\s+((?:\w+\.)?\w+)', re.I
)
RE_TRIG = re.compile(
    r"CREATE\s+(?:OR\s+REPLACE\s+)?TRIGGER\s+(\w+)", re.I
)
RE_TABLE = re.compile(
    r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:public\.)?(\w+)", re.I
)
RE_COL = re.compile(
    r"ALTER\s+TABLE\s+(?:public\.)?(\w+)\s+ADD\s+COLUMN\s+"
    r"(?:IF\s+NOT\s+EXISTS\s+)?(\w+)",
    re.I,
)
RE_CRON = re.compile(r"cron\.schedule\(\s*'([^']+)'", re.I)
RE_INDEX = re.compile(
    r"CREATE\s+(?:UNIQUE\s+)?INDEX\s+(?:CONCURRENTLY\s+)?"
    r"(?:IF\s+NOT\s+EXISTS\s+)?(\w+)",
    re.I,
)


def collect():
    files = sorted(MIG_DIR.glob("*.sql"))
    rows = []  # (category, obj, detail, migration)
    seen = set()

    def add(cat, obj, detail, mig):
        key = (cat, obj, detail)
        if key in seen:
            return
        seen.add(key)
        rows.append((cat, obj, detail, mig))

    for f in files:
        txt = strip_sql_comments(
            f.read_text(encoding="utf-8", errors="ignore")
        )
        mig = f.stem
        for m in RE_FUNC.finditer(txt):
            add("function", m.group(1), "", mig)
        for m in RE_POLICY.finditer(txt):
            pol, tbl = m.group(1), m.group(2)
            schema, t = tbl.split(".", 1) if "." in tbl else ("public", tbl)
            add("policy", f"{schema}.{t}", pol, mig)
        for m in RE_TRIG.finditer(txt):
            add("trigger", m.group(1), "", mig)
        for m in RE_TABLE.finditer(txt):
            if m.group(1).lower() == "if":
                continue
            add("table", m.group(1), "", mig)
        for m in RE_COL.finditer(txt):
            add("column", m.group(1), m.group(2), mig)
        for m in RE_CRON.finditer(txt):
            add("cron", m.group(1), "", mig)
        for m in RE_INDEX.finditer(txt):
            add("index", m.group(1), "", mig)

    return files, rows


def esc(s: str) -> str:
    return s.replace("'", "''")


def write_drift_check(files, rows):
    vals = ",\n".join(
        f"  ('{c}','{esc(o)}','{esc(d)}','{esc(mig)}')"
        for c, o, d, mig in rows
    )
    sql = f"""-- ============================================================
-- PikTag migration drift check
-- AUTO-GENERATED by scripts/gen_migration_drift_check.py from
-- {len(files)} migration files. Do not hand-edit — regenerate.
--
-- Any row with present=false ⇒ that object is MISSING from this
-- database ⇒ the source migration was never (fully) applied.
-- Some false rows are EXPECTED (objects later superseded/dropped
-- by a newer migration, or features retired). Cross-reference
-- before "fixing" — see scripts/migration_remediation.sql for the
-- 2026-05 audit of which falses were real vs intentional.
-- ============================================================
WITH expected(category, obj, detail, migration) AS (
  VALUES
{vals}
)
SELECT
  e.migration,
  e.category,
  e.obj,
  NULLIF(e.detail,'') AS detail,
  CASE e.category
    WHEN 'function' THEN EXISTS(
      SELECT 1 FROM pg_proc p
      JOIN pg_namespace n ON n.oid = p.pronamespace
      WHERE n.nspname = 'public' AND p.proname = e.obj)
    WHEN 'policy' THEN EXISTS(
      SELECT 1 FROM pg_policies
      WHERE schemaname = split_part(e.obj,'.',1)
        AND tablename  = split_part(e.obj,'.',2)
        AND policyname = e.detail)
    WHEN 'trigger' THEN EXISTS(
      SELECT 1 FROM pg_trigger
      WHERE tgname = e.obj AND NOT tgisinternal)
    WHEN 'table' THEN EXISTS(
      SELECT 1 FROM information_schema.tables
      WHERE table_schema = 'public' AND table_name = e.obj)
    WHEN 'column' THEN EXISTS(
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = e.obj AND column_name = e.detail)
    WHEN 'cron' THEN EXISTS(
      SELECT 1 FROM cron.job WHERE jobname = e.obj)
    WHEN 'index' THEN EXISTS(
      SELECT 1 FROM pg_indexes
      WHERE schemaname = 'public' AND indexname = e.obj)
  END AS present
FROM expected e
ORDER BY present ASC, e.migration, e.category, e.obj;
"""
    p = OUT_DIR / "migration_drift_check.sql"
    p.write_text(sql, encoding="utf-8")
    return p


def write_fk_audit():
    sql = """-- ============================================================
-- PikTag foreign-key audit
-- AUTO-GENERATED by scripts/gen_migration_drift_check.py
--
-- Dumps EVERY foreign key in schema public with its ON DELETE /
-- ON UPDATE rule. NOT derived from migrations — base-schema FKs
-- aren't in any migration file, which is exactly why the
-- "can't delete a Vibe" bug (2026-05) went undetected: the
-- object-existence drift check structurally cannot see a wrong
-- delete-rule on an FK no migration declares.
--
-- HOW TO READ: rows are ordered dangerous-first. An FK with
-- delete_rule = 'NO ACTION' or 'RESTRICT' BLOCKS deletion of the
-- referenced row while any child row points at it. That is a
-- latent "X can't be deleted" bug IFF there's a user-facing
-- delete path for the referenced table. For each such row ask:
--   "Can a user delete a <referenced_table> row in the app?"
--   If yes and the child rows shouldn't block it → the FK should
--   be ON DELETE SET NULL (keep child, drop the link) or CASCADE
--   (child is owned by parent). See migration
--   20260516000000_scan_session_fk_set_null.sql for the pattern.
-- ============================================================
SELECT
  con.conrelid::regclass::text  AS referencing_table,
  att.attname                   AS referencing_column,
  con.confrelid::regclass::text AS referenced_table,
  con.conname                   AS constraint_name,
  CASE con.confdeltype
    WHEN 'a' THEN 'NO ACTION'
    WHEN 'r' THEN 'RESTRICT'
    WHEN 'c' THEN 'CASCADE'
    WHEN 'n' THEN 'SET NULL'
    WHEN 'd' THEN 'SET DEFAULT'
  END AS on_delete,
  CASE con.confupdtype
    WHEN 'a' THEN 'NO ACTION'
    WHEN 'r' THEN 'RESTRICT'
    WHEN 'c' THEN 'CASCADE'
    WHEN 'n' THEN 'SET NULL'
    WHEN 'd' THEN 'SET DEFAULT'
  END AS on_update,
  -- Dangerous = blocks parent delete. Surfaced first.
  (con.confdeltype IN ('a','r')) AS blocks_parent_delete
FROM pg_constraint con
JOIN pg_class      rel ON rel.oid = con.conrelid
JOIN pg_namespace  ns  ON ns.oid  = rel.relnamespace
JOIN pg_attribute  att ON att.attrelid = con.conrelid
                      AND att.attnum   = ANY (con.conkey)
WHERE con.contype = 'f'
  AND ns.nspname  = 'public'
ORDER BY blocks_parent_delete DESC,
         referenced_table,
         referencing_table;
"""
    p = OUT_DIR / "fk_audit.sql"
    p.write_text(sql, encoding="utf-8")
    return p


def main():
    files, rows = collect()
    p1 = write_drift_check(files, rows)
    p2 = write_fk_audit()
    print(f"Wrote {p1}")
    print(f"Wrote {p2}")
    print(f"Migration files scanned: {len(files)}")
    print(f"Objects checked: {len(rows)}")
    for cat, n in sorted(Counter(r[0] for r in rows).items()):
        print(f"  {cat}: {n}")


if __name__ == "__main__":
    main()
