# captions.py — App Store screenshot captions, 17 locales.
# Auto-assembled 2026-06-12 (en/zh-TW authored; 15 via in-house localization).
# Each CARDS_BY_LANG[lang][i] = (title, subtitle, source_png). \n in a title
# forces a 2-line break. Shared by build_screenshot.py + build_screenshot_ipad.py.

SOURCES = ['04-profile.png', '05-qr.png', '01-cardscan.png', '03-ai.png', '06-map.png', '02-stats.png']

CARDS_BY_LANG = {
    'en': [
        ('Let people find you', 'The right people find you by your tags', '04-profile.png'),
        ('One scan, friends filed', 'One QR per event — friends auto-organized', '05-qr.png'),
        ('Scan a card, remember them', 'Auto-saved with tags in 3 seconds', '01-cardscan.png'),
        ('AI breaks the ice, 3 openers ready', 'Personalized from what you two share', '03-ai.png'),
        ('Your people, on a map', 'Nearby friends who share your tags', '06-map.png'),
        ('Your circle, in numbers', 'Who scanned you, who tapped you', '02-stats.png'),
    ],
    'zh-TW': [
        ('你的人脈，一張圖看見', '好友如何彼此連結，還有你可能認識的人', '01-network.png'),
        ('讓別人搜得到你', '朋友需要你這種人時，搜標籤就找到你', '04-profile.png'),
        ('掃一下，QR 跟名片都在這', '對到 QR 自動加好友，名片拍一下自動建檔', '03-scan.png'),
        ('不知道怎麼開口，AI 給你 3 句', '從你們的共同點，接回上次停下的話題', '03-ai.png'),
        ('附近誰跟你同頻，地圖看得見', '同標籤的朋友，就在你身邊', '06-map.png'),
        ('你的影響力，看得見的成長', '誰掃了你、誰點了你，一張表全記得', '02-stats.png'),
    ],
    'zh-CN': [
        ('让对的人\n找到你', '需要你这种人时，搜标签就找到你', '04-profile.png'),
        ('见面扫一下\n朋友自动归档', '一场活动一个 QR，认识谁都记得住', '05-qr.png'),
        ('拍张名片\n3 秒记住一个人', '自动建档、自动加标签，想得起他是谁', '01-cardscan.png'),
        ('不知怎么开口\nAI 给你 3 句', '从你们的共同点，接回上次的话题', '03-ai.png'),
        ('附近的同频人\n地图看得见', '同标签的朋友，就在你身边', '06-map.png'),
        ('你的人脉\n看得见的成长', '谁扫了你、谁点了你，一表全记得', '02-stats.png'),
    ],
    'ja': [
        ('あなたが\n見つけてもらえる', '必要とする人が、タグ検索で出会える', '04-profile.png'),
        ('会ったら一度\nスキャン', 'イベントごとに QR、誰でも記憶に残る', '05-qr.png'),
        ('名刺を一枚\n3秒で覚える', '自動保存・自動タグ付けで思い出せる', '01-cardscan.png'),
        ('切り出せない時\nAI が3つの一言', '二人の共通点から、続きの話題へ', '03-ai.png'),
        ('近くの同志を\n地図で発見', '同じタグの友だちが、すぐそばに', '06-map.png'),
        ('あなたの人脈\n伸びが見える', '誰がスキャンし、誰が見たか一目で', '02-stats.png'),
    ],
    'ko': [
        ('사람들이\n당신을 찾도록', '필요할 때, 태그 검색으로 당신을 발견', '04-profile.png'),
        ('만나면 한 번\n스캔하면 정리 끝', '행사마다 QR 하나, 누구든 기억해요', '05-qr.png'),
        ('명함 한 장\n3초면 기억', '자동 저장·자동 태그로 떠올릴 수 있게', '01-cardscan.png'),
        ('말 꺼내기 힘들 때\nAI가 3마디', '둘의 공통점에서, 끊긴 대화를 이어요', '03-ai.png'),
        ('가까운 친구를\n지도에서', '같은 태그의 친구가, 바로 곁에', '06-map.png'),
        ('당신의 인맥\n자라는 게 보여요', '누가 스캔했고, 누가 봤는지 한눈에', '02-stats.png'),
    ],
    'de': [
        ('Lass dich\nfinden', 'Die richtigen Leute finden dich über deine Tags', '04-profile.png'),
        ('Ein Scan,\nalle sortiert', 'Ein QR pro Event – Kontakte automatisch geordnet', '05-qr.png'),
        ('Karte scannen,\nKopf merken', 'Automatisch gespeichert, getaggt in 3 Sekunden', '01-cardscan.png'),
        ('KI bricht\ndas Eis', '3 Einstiege aus dem, was euch verbindet', '03-ai.png'),
        ('Deine Leute\nauf der Karte', 'Freunde in der Nähe mit denselben Tags', '06-map.png'),
        ('Dein Netzwerk\nin Zahlen', 'Wer dich gescannt, wer dich getippt hat', '02-stats.png'),
    ],
    'fr': [
        ('Fais-toi\ntrouver', 'Les bonnes personnes te trouvent par tes tags', '04-profile.png'),
        ('Un scan,\namis classés', 'Un QR par événement, contacts triés tout seuls', '05-qr.png'),
        ('Scanne une\ncarte, retiens', 'Enregistré et taggé en 3 secondes', '01-cardscan.png'),
        ("L'IA brise\nla glace", '3 phrases tirées de vos points communs', '03-ai.png'),
        ('Tes proches,\nsur la carte', 'Des amis tout près avec les mêmes tags', '06-map.png'),
        ('Ton réseau,\nen chiffres', "Qui t'a scanné, qui t'a cliqué", '02-stats.png'),
    ],
    'es': [
        ('Deja que te\nencuentren', 'Las personas correctas te hallan por tus tags', '04-profile.png'),
        ('Un escaneo,\namigos listos', 'Un QR por evento, contactos ordenados solos', '05-qr.png'),
        ('Escanea y\nrecuérdalo', 'Guardado y etiquetado en 3 segundos', '01-cardscan.png'),
        ('La IA rompe\nel hielo', '3 frases a partir de lo que comparten', '03-ai.png'),
        ('Tu gente,\nen el mapa', 'Amigos cerca con tus mismos tags', '06-map.png'),
        ('Tu red,\nen números', 'Quién te escaneó, quién te tocó', '02-stats.png'),
    ],
    'pt': [
        ('Deixe que\nte encontrem', 'As pessoas certas te acham pelas suas tags', '04-profile.png'),
        ('Um scan,\ntudo no lugar', 'Um QR por evento e os amigos se organizam sozinhos', '05-qr.png'),
        ('Fotografe\no cartão', 'Salvo com tags em 3 segundos', '01-cardscan.png'),
        ('A AI quebra\no gelo', '3 frases prontas a partir do que vocês têm em comum', '03-ai.png'),
        ('Sua gente\nno mapa', 'Amigos por perto que curtem as mesmas tags', '06-map.png'),
        ('Sua rede\nem números', 'Quem te escaneou, quem te tocou', '02-stats.png'),
    ],
    'it': [
        ('Fatti\ntrovare', 'Le persone giuste ti trovano dalle tue tag', '04-profile.png'),
        ('Uno scan,\namici a posto', 'Un QR per evento e gli amici si ordinano da soli', '05-qr.png'),
        ('Scatta il\nbiglietto', 'Salvato con le tag in 3 secondi', '01-cardscan.png'),
        ("L'AI rompe\nil ghiaccio", '3 battute pronte da ciò che avete in comune', '03-ai.png'),
        ('I tuoi\nsulla mappa', 'Amici vicini con le tue stesse tag', '06-map.png'),
        ('La tua rete\nin numeri', 'Chi ti ha scansionato, chi ti ha cliccato', '02-stats.png'),
    ],
    'ru': [
        ('Пусть тебя\nнайдут', 'Нужные люди находят тебя по тегам', '04-profile.png'),
        ('Скан, друзья\nна местах', 'Один QR на встречу, друзья сами в порядке', '05-qr.png'),
        ('Сними\nвизитку', 'Сохранили с тегами за 3 секунды', '01-cardscan.png'),
        ('AI начнёт\nразговор', '3 фразы из того, что у вас общего', '03-ai.png'),
        ('Свои —\nна карте', 'Друзья рядом с такими же тегами', '06-map.png'),
        ('Сеть\nв цифрах', 'Кто сканировал, кто заходил', '02-stats.png'),
    ],
    'tr': [
        ('Seni\nbulsunlar', 'Doğru kişiler etiketlerinden seni bulsun', '04-profile.png'),
        ('Bir kare,\ndostlar hazır', 'Etkinlik başına tek QR, herkesi hatırla', '05-qr.png'),
        ('Kartı çek,\nonu unutma', '3 saniyede etiketlerle otomatik kaydet', '01-cardscan.png'),
        ('AI buzu kırar,\n3 cümle hazır', 'İkinizin ortak yönlerine özel açılışlar', '03-ai.png'),
        ('Çevren\nharitada', 'Seninle aynı etiketli yakın dostlar', '06-map.png'),
        ('Çevren\nsayılarla', 'Kim seni taradı, kim sana dokundu', '02-stats.png'),
    ],
    'id': [
        ('Biar kamu\nditemukan', 'Orang yang tepat temukan kamu lewat tag', '04-profile.png'),
        ('Sekali scan,\nteman tertata', 'Satu QR per acara, semua diingat', '05-qr.png'),
        ('Scan kartu,\nlangsung ingat', 'Tersimpan otomatis dengan tag, 3 detik', '01-cardscan.png'),
        ('AI cairkan\nsuasana', '3 pembuka dari kesamaan kalian berdua', '03-ai.png'),
        ('Lingkaranmu\ndi peta', 'Teman terdekat dengan tag yang sama', '06-map.png'),
        ('Relasimu\ndalam angka', 'Siapa scan kamu, siapa ketuk kamu', '02-stats.png'),
    ],
    'vi': [
        ('Để họ\ntìm ra bạn', 'Đúng người tìm thấy bạn qua các tag', '04-profile.png'),
        ('Quét một lần,\nbạn vào nếp', 'Mỗi sự kiện một QR, nhớ hết mọi người', '05-qr.png'),
        ('Quét card,\nnhớ ngay họ', 'Tự lưu kèm tag chỉ trong 3 giây', '01-cardscan.png'),
        ('AI phá băng,\nsẵn 3 câu', 'Gợi mở từ điểm chung của hai bạn', '03-ai.png'),
        ('Bạn bè\ntrên bản đồ', 'Người gần bên chung tag với bạn', '06-map.png'),
        ('Quan hệ\nqua con số', 'Ai quét bạn, ai chạm vào bạn', '02-stats.png'),
    ],
    'th': [
        ('ให้คนเจอคุณ', 'คนที่ใช่เจอคุณได้จากแท็ก', '04-profile.png'),
        ('สแกนครั้งเดียว\nเพื่อนเข้าที่', 'หนึ่งงานหนึ่ง QR จำได้ทุกคน', '05-qr.png'),
        ('ถ่ายนามบัตร\nจำเขาได้', 'บันทึกพร้อมแท็กใน 3 วินาที', '01-cardscan.png'),
        ('AI ช่วยเปิดบท\n3 ประโยคพร้อม', 'ปรับจากสิ่งที่คุณสองคนมีร่วมกัน', '03-ai.png'),
        ('คนของคุณ\nบนแผนที่', 'เพื่อนใกล้ตัวที่แท็กตรงกัน', '06-map.png'),
        ('คอนเนกชัน\nเป็นตัวเลข', 'ใครสแกนคุณ ใครแตะหาคุณ', '02-stats.png'),
    ],
    'ar': [
        ('دع الناس\nيجدونك', 'من تبحث عنهم يجدونك بوسومك', '04-profile.png'),
        ('مسحة واحدة\nوأصدقاؤك بترتيب', 'رمز QR لكل مناسبة يحفظ الجميع', '05-qr.png'),
        ('صوّر البطاقة\nتذكّره دائماً', 'حفظ تلقائي بالوسوم في 3 ثوانٍ', '01-cardscan.png'),
        ('AI يكسر الجمود\nبثلاث جمل', 'مخصصة مما تشتركان فيه معاً', '03-ai.png'),
        ('أشخاصك\nعلى الخريطة', 'أصدقاء قريبون يشاركونك وسومك', '06-map.png'),
        ('شبكتك\nبالأرقام', 'من مسحك ومن تفاعل معك', '02-stats.png'),
    ],
    'hi': [
        ('लोग आपको\nखोज पाएँ', 'सही लोग आपके टैग से आप तक', '04-profile.png'),
        ('एक स्कैन,\nदोस्त सहेजे', 'हर इवेंट एक QR, हर कोई याद', '05-qr.png'),
        ('कार्ड स्कैन करें\nउन्हें याद रखें', 'टैग के साथ 3 सेकंड में सेव', '01-cardscan.png'),
        ('AI तोड़े झिझक,\n3 लाइन तैयार', 'आपकी साझा बातों से बनी हुई', '03-ai.png'),
        ('आपके लोग,\nनक्शे पर', 'पास के दोस्त, वही टैग साझा', '06-map.png'),
        ('आपका नेटवर्क,\nआँकड़ों में', 'किसने स्कैन किया, किसने छुआ', '02-stats.png'),
    ],
}

CHIP_BY_LANG = {
    'en': ('3 seconds flat', 'AI adds the tags'),
    'zh-TW': ('3 秒就好', 'AI 自動加標籤'),
    'zh-CN': ('3 秒搞定', 'AI 自动加标签'),
    'ja': ('3秒で完了', 'AI が自動タグ付け'),
    'ko': ('3초면 끝', 'AI가 태그 추가'),
    'de': ('In 3 Sekunden', 'KI taggt'),
    'fr': ('En 3 sec', "L'IA tague"),
    'es': ('En 3 seg', 'La IA etiqueta'),
    'pt': ('3 segundos', 'AI põe as tags'),
    'it': ('3 secondi', "Tag dall'AI"),
    'ru': ('3 секунды', 'Теги от AI'),
    'tr': ('3 saniye', 'AI etiketler'),
    'id': ('3 detik', 'AI beri tag'),
    'vi': ('3 giây', 'AI gắn tag'),
    'th': ('แค่ 3 วินาที', 'AI ใส่แท็กให้'),
    'ar': ('3 ثوانٍ فقط', 'AI يضيف الوسوم'),
    'hi': ('बस 3 सेकंड', 'AI टैग जोड़े'),
}
