-- 20260910020000_tag_alias_provenance.sql
--
-- Record where each tag alias came from.
--
-- WHY
-- auto-link-concepts is about to start generating cross-language aliases
-- with an LLM, across all 19 app locales. Four of those (ar, bn, hi, ur)
-- are languages nobody on this side can spot-check, and an alias is not
-- like a UI string: tag_aliases.alias is globally UNIQUE, so a wrong one
-- permanently occupies that string for every concept, and the damage is
-- silent -- searches in that language quietly return the wrong people,
-- and the users best placed to notice are the least likely to report it.
--
-- Today those aliases would be indistinguishable from the hand-curated
-- ones. If Bengali output turns out to be poor in three months, there is
-- no query that separates it from the curated 古著/咖啡/水晶 bridges, so
-- the only options would be keep everything or audit by hand.
--
-- One nullable column turns that irreversible decision into a reversible
-- one:
--
--   DELETE FROM tag_aliases WHERE source = 'llm' AND language = 'bn';
--
-- VALUES
--   'legacy' — existed before this column. Origin genuinely unknown.
--   'seed'   — written by a seed or curated migration.
--   'llm'    — a translation generated by the model.
--   NULL     — written by the linker for a tag's own name.
--
-- 'tag' is deliberately absent even though the linker writes three such
-- aliases per tag. Those three are upserts on `alias`, and supabase-js
-- upsert writes every column it is given, so labelling them would rewrite
-- the source of whatever row already sat there. The alias-resolution path
-- in particular upserts the very alias that resolved the tag -- usually a
-- curated one -- so stamping it would quietly erode the 'seed' labels on
-- every run until the curated set was indistinguishable from everything
-- else. Those rows are left NULL instead: less information, but no lying.
--
-- NULL is therefore legal on purpose, and a column DEFAULT is deliberately
-- omitted so nothing is labelled by accident.
--
-- Note on the backfill: every existing row becomes 'legacy', NOT 'seed'.
-- The table today holds both seed-migration rows and linker-written ones
-- and nothing distinguishes them after the fact. Calling them all 'seed'
-- would assert something we do not know, in the one table whose entire
-- job from now on is to be truthful about origin.

ALTER TABLE public.tag_aliases
  ADD COLUMN IF NOT EXISTS source text;

UPDATE public.tag_aliases
SET source = 'legacy'
WHERE source IS NULL;

ALTER TABLE public.tag_aliases
  DROP CONSTRAINT IF EXISTS tag_aliases_source_check;

ALTER TABLE public.tag_aliases
  ADD CONSTRAINT tag_aliases_source_check
  CHECK (source IS NULL OR source IN ('legacy', 'seed', 'llm'));

-- Supports both the audit query ("show me everything the model wrote in
-- language X") and the bulk revert above.
CREATE INDEX IF NOT EXISTS idx_tag_aliases_source_language
  ON public.tag_aliases (source, language);

-- Read-only audit surface: how many aliases each source/language pair
-- holds, and how many of them are actually reachable from a real tag.
-- Answers "is the model's Bengali output doing anything?" without
-- exporting the table.
CREATE OR REPLACE FUNCTION public.admin_alias_provenance()
RETURNS TABLE (
  source        text,
  language      text,
  alias_count   bigint,
  concept_count bigint,
  tagged_count  bigint
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT
    COALESCE(a.source, '(unlabelled)') AS source,
    COALESCE(a.language, '(none)')     AS language,
    COUNT(*)                           AS alias_count,
    COUNT(DISTINCT a.concept_id)       AS concept_count,
    -- Aliases whose concept actually has at least one tag on it. An alias
    -- pointing at a concept nobody tagged bridges nothing, so this is the
    -- column that says whether a language is earning its keep.
    COUNT(*) FILTER (
      WHERE EXISTS (SELECT 1 FROM public.piktag_tags t WHERE t.concept_id = a.concept_id)
    )                                  AS tagged_count
  FROM public.tag_aliases a
  GROUP BY 1, 2
  ORDER BY 1, 3 DESC;
$$;

-- Admin/ops only. Named roles, never FROM PUBLIC alone -- on Supabase a
-- REVOKE aimed at PUBLIC leaves the default anon/authenticated grant in
-- place (see 20260909230000).
REVOKE EXECUTE ON FUNCTION public.admin_alias_provenance()
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.admin_alias_provenance()
  TO postgres, service_role;

DO $$
DECLARE v_legacy bigint;
BEGIN
  SELECT COUNT(*) INTO v_legacy FROM public.tag_aliases WHERE source = 'legacy';
  RAISE NOTICE 'tag alias provenance: % existing aliases labelled legacy.', v_legacy;
END $$;
