-- 20260430140000_block_user_rpc_and_block_aware_triggers.sql
--
-- Two coordinated fixes for the block flow:
--
-- 1. New RPC `block_user(p_blocked_id uuid)` that does the entire block
--    cascade atomically:
--      * Insert into piktag_blocks
--      * Delete bilateral piktag_follows (both A→B and B→A)
--      * Delete bilateral piktag_close_friends
--      * Delete piktag_notifications produced BY the blocked user
--        toward the blocker (so the blocker's notification list gets
--        clean of past actor activity, not just future)
--    Replaces the client-side direct upsert into piktag_blocks, which
--    used to leave follows / close-friends / notifications in a stale
--    state. After this RPC runs, blocking actually does what users
--    expect: the other person disappears from feed, follow count,
--    close-friend list, AND notifications.
--
-- 2. Three notification triggers gain a `NOT EXISTS piktag_blocks`
--    guard so that FUTURE inserts also respect the block in either
--    direction:
--      * notify_follow      (was bound to dead piktag_followers; rebind
--                            to piktag_follows AND add block check)
--      * notify_tag_added   (on piktag_user_tags)
--      * notify_ask_posted  (on piktag_asks; check inside fan-out loop)
--
-- piktag_connections rows are intentionally NOT cleared by block — they
-- are the relationship-history graveyard. If the blocker ever unblocks,
-- the old met_at / hidden tags / sticky notes are preserved. Same
-- memory-preservation logic as the unfollow path.
--
-- Idempotent: CREATE OR REPLACE FUNCTION + DROP TRIGGER IF EXISTS.

CREATE EXTENSION IF NOT EXISTS pg_net;

-- =============================================================================
-- 1. block_user(p_blocked_id) RPC
-- =============================================================================

CREATE OR REPLACE FUNCTION public.block_user(p_blocked_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_blocker_id uuid := auth.uid();
BEGIN
  IF v_blocker_id IS NULL THEN
    RAISE EXCEPTION 'auth required';
  END IF;
  IF p_blocked_id IS NULL OR p_blocked_id = v_blocker_id THEN
    RAISE EXCEPTION 'cannot block null or self';
  END IF;

  -- 1. Insert the block record (idempotent — re-blocking is a no-op).
  INSERT INTO public.piktag_blocks (blocker_id, blocked_id)
  VALUES (v_blocker_id, p_blocked_id)
  ON CONFLICT (blocker_id, blocked_id) DO NOTHING;

  -- 2. Bilateral follow cleanup. Removes the blocked user from feeds,
  --    follow-count UI, and any RPC that joins on piktag_follows.
  DELETE FROM public.piktag_follows
  WHERE (follower_id = v_blocker_id AND following_id = p_blocked_id)
     OR (follower_id = p_blocked_id AND following_id = v_blocker_id);

  -- 3. Bilateral close-friend cleanup. Without this, the blocker's
  --    close-friend list (or their close-friend status FROM the blocked
  --    user) lingers as a stale, semantically-broken entry.
  DELETE FROM public.piktag_close_friends
  WHERE (user_id = v_blocker_id AND close_friend_id = p_blocked_id)
     OR (user_id = p_blocked_id AND close_friend_id = v_blocker_id);

  -- 4. Clear the blocker's prior notifications generated by the blocked
  --    user. Notifications carry actor_user_id in their data JSONB; we
  --    match on that. Only the blocker's notifications are touched —
  --    the blocked user's notifications stay intact (they shouldn't
  --    know they were blocked).
  DELETE FROM public.piktag_notifications
  WHERE user_id = v_blocker_id
    AND (data->>'actor_user_id') = p_blocked_id::text;
END;
$$;

REVOKE ALL ON FUNCTION public.block_user(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.block_user(uuid) TO authenticated;

-- =============================================================================
-- 2. notify_follow — rebind to piktag_follows + add block check
--    The original migration bound the trigger to piktag_followers (a
--    parallel table that the client never writes to), so the follow
--    notification has been silently dead this whole time. Fix the
--    binding here AND add the block guard in the same pass.
-- =============================================================================

CREATE OR REPLACE FUNCTION public.notify_follow()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_recipient      uuid;
  v_actor          uuid;
  v_actor_username text;
  v_actor_avatar   text;
  v_already_exists boolean;
  v_blocked        boolean;
  v_body           text := 'started following you';
  v_dedup_window   interval := interval '24 hours';
  v_push_token     text;
  v_auth_key       text;
  v_base_url       text;
BEGIN
  v_recipient := NEW.following_id;
  v_actor     := NEW.follower_id;

  IF v_recipient IS NULL OR v_actor IS NULL OR v_recipient = v_actor THEN
    RETURN NEW;
  END IF;

  -- Block guard: if either party has blocked the other, drop the
  -- notification silently. We check both directions because either side
  -- of the block should be sufficient to suppress noise.
  SELECT EXISTS (
    SELECT 1 FROM public.piktag_blocks
     WHERE (blocker_id = v_recipient AND blocked_id = v_actor)
        OR (blocker_id = v_actor     AND blocked_id = v_recipient)
  ) INTO v_blocked;
  IF v_blocked THEN
    RETURN NEW;
  END IF;

  -- 24h dedup
  SELECT EXISTS (
    SELECT 1
      FROM public.piktag_notifications
     WHERE user_id   = v_recipient
       AND type      = 'follow'
       AND data->>'actor_user_id' = v_actor::text
       AND created_at > now() - v_dedup_window
  ) INTO v_already_exists;

  IF v_already_exists THEN
    RETURN NEW;
  END IF;

  SELECT COALESCE(p.username, p.full_name, ''),
         p.avatar_url
    INTO v_actor_username,
         v_actor_avatar
    FROM public.piktag_profiles p
   WHERE p.id = v_actor;

  INSERT INTO public.piktag_notifications (
    user_id, type, title, body, data, is_read, created_at
  )
  VALUES (
    v_recipient,
    'follow',
    '',
    v_body,
    jsonb_build_object(
      'actor_user_id', v_actor,
      'username',      COALESCE(v_actor_username, ''),
      'avatar_url',    v_actor_avatar,
      'follow_id',     NEW.id
    ),
    false,
    now()
  );

  -- Push notification (best-effort)
  BEGIN
    SELECT decrypted_secret INTO v_auth_key
      FROM vault.decrypted_secrets
     WHERE name = 'piktag_service_role_key' LIMIT 1;
    SELECT decrypted_secret INTO v_base_url
      FROM vault.decrypted_secrets
     WHERE name = 'piktag_supabase_url' LIMIT 1;
    SELECT push_token INTO v_push_token
      FROM public.piktag_profiles
     WHERE id = v_recipient LIMIT 1;

    IF v_auth_key IS NOT NULL
       AND v_push_token IS NOT NULL
       AND length(v_push_token) > 0 THEN
      PERFORM net.http_post(
        url     := 'https://exp.host/--/api/v2/push/send',
        headers := jsonb_build_object(
          'Content-Type',  'application/json',
          'Accept',        'application/json',
          'Authorization', 'Bearer ' || v_auth_key
        ),
        body    := jsonb_build_object(
          'to',       v_push_token,
          'title',    COALESCE(NULLIF(v_actor_username, ''), 'PikTag'),
          'body',     v_body,
          'data',     jsonb_build_object(
            'type',          'follow',
            'actor_user_id', v_actor,
            'follow_id',     NEW.id
          ),
          'sound',    'default',
          'priority', 'high'
        )
      );
    END IF;
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'notify_follow push dispatch failed: %', SQLERRM;
  END;

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.notify_follow() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.notify_follow() TO postgres, service_role;

-- Drop the dead trigger on piktag_followers (the parallel table that
-- the client never writes to) and rebind to piktag_follows where it
-- actually fires.
DROP TRIGGER IF EXISTS trg_notify_follow ON public.piktag_followers;
DROP TRIGGER IF EXISTS trg_notify_follow ON public.piktag_follows;
CREATE TRIGGER trg_notify_follow
AFTER INSERT ON public.piktag_follows
FOR EACH ROW EXECUTE FUNCTION public.notify_follow();

-- =============================================================================
-- 3. notify_tag_added — add block check
-- =============================================================================

CREATE OR REPLACE FUNCTION public.notify_tag_added()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_recipient        uuid;
  v_actor            uuid;
  v_actor_username   text;
  v_actor_full_name  text;
  v_actor_avatar     text;
  v_tag_name         text;
  v_already_exists   boolean;
  v_blocked          boolean;
  v_body             text;
  v_data             jsonb;
  v_recipient_token  text;
  v_auth_key         text;
  v_base_url         text;
  v_display_name     text;
BEGIN
  v_recipient := NEW.user_id;

  BEGIN
    v_actor := NULLIF(current_setting('request.jwt.claim.sub', true), '')::uuid;
  EXCEPTION WHEN OTHERS THEN
    v_actor := NULL;
  END;

  IF v_actor IS NULL THEN
    RETURN NEW;
  END IF;

  IF v_recipient IS NULL OR v_recipient = v_actor THEN
    RETURN NEW;
  END IF;

  -- Block guard (same bilateral check as notify_follow).
  SELECT EXISTS (
    SELECT 1 FROM public.piktag_blocks
     WHERE (blocker_id = v_recipient AND blocked_id = v_actor)
        OR (blocker_id = v_actor     AND blocked_id = v_recipient)
  ) INTO v_blocked;
  IF v_blocked THEN
    RETURN NEW;
  END IF;

  -- 24h dedup
  SELECT EXISTS (
    SELECT 1 FROM public.piktag_notifications
     WHERE user_id   = v_recipient
       AND type      = 'tag_added'
       AND data->>'actor_user_id' = v_actor::text
       AND data->>'tag_id'        = NEW.tag_id::text
       AND created_at > now() - interval '24 hours'
  ) INTO v_already_exists;

  IF v_already_exists THEN
    RETURN NEW;
  END IF;

  SELECT username, full_name, avatar_url
    INTO v_actor_username, v_actor_full_name, v_actor_avatar
    FROM public.piktag_profiles
   WHERE id = v_actor LIMIT 1;

  SELECT name INTO v_tag_name
    FROM public.piktag_tags
   WHERE id = NEW.tag_id LIMIT 1;

  v_display_name := COALESCE(NULLIF(v_actor_full_name, ''), NULLIF(v_actor_username, ''), 'Someone');
  v_body := 'tagged you as #' || COALESCE(v_tag_name, 'a tag');

  v_data := jsonb_build_object(
    'actor_user_id', v_actor,
    'username',      COALESCE(v_actor_username, ''),
    'avatar_url',    v_actor_avatar,
    'tag_id',        NEW.tag_id,
    'tag_name',      COALESCE(v_tag_name, ''),
    'user_tag_id',   NEW.id
  );

  INSERT INTO public.piktag_notifications (
    user_id, type, title, body, data, is_read, created_at
  ) VALUES (
    v_recipient, 'tag_added', '', v_body, v_data, false, now()
  );

  -- Push (best-effort)
  BEGIN
    SELECT decrypted_secret INTO v_auth_key
      FROM vault.decrypted_secrets
     WHERE name = 'piktag_service_role_key' LIMIT 1;
    SELECT decrypted_secret INTO v_base_url
      FROM vault.decrypted_secrets
     WHERE name = 'piktag_supabase_url' LIMIT 1;
    SELECT push_token INTO v_recipient_token
      FROM public.piktag_profiles
     WHERE id = v_recipient LIMIT 1;

    IF v_auth_key IS NOT NULL
       AND v_recipient_token IS NOT NULL
       AND length(v_recipient_token) > 0 THEN
      PERFORM net.http_post(
        url     := 'https://exp.host/--/api/v2/push/send',
        headers := jsonb_build_object(
          'Content-Type',  'application/json',
          'Accept',        'application/json',
          'Authorization', 'Bearer ' || v_auth_key
        ),
        body    := jsonb_build_object(
          'to',       v_recipient_token,
          'title',    v_display_name,
          'body',     v_body,
          'data',     jsonb_build_object(
            'type',          'tag_added',
            'actor_user_id', v_actor,
            'tag_id',        NEW.tag_id,
            'tag_name',      COALESCE(v_tag_name, '')
          ),
          'sound',    'default',
          'priority', 'high'
        )
      );
    END IF;
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'notify_tag_added push dispatch failed: %', SQLERRM;
  END;

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.notify_tag_added() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.notify_tag_added() TO postgres, service_role;

-- =============================================================================
-- 4. notify_ask_posted — add block check inside the fan-out loop
-- =============================================================================

CREATE OR REPLACE FUNCTION public.notify_ask_posted()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_actor uuid := NEW.author_id;
  v_actor_full_name text;
  v_actor_username text;
  v_actor_avatar text;
  v_recipient record;
  v_already_exists boolean;
  v_blocked boolean;
  v_body text;
  v_actor_label text;
  v_auth_key text;
  v_base_url text;
  v_push_token text;
BEGIN
  IF NEW.is_active IS DISTINCT FROM true THEN
    RETURN NEW;
  END IF;

  SELECT full_name, username, avatar_url
    INTO v_actor_full_name, v_actor_username, v_actor_avatar
    FROM public.piktag_profiles
   WHERE id = v_actor LIMIT 1;

  v_actor_label := COALESCE(
    NULLIF(v_actor_full_name, ''),
    NULLIF(v_actor_username, ''),
    'PikTag'
  );

  v_body := '發了 Ask · ' ||
            CASE
              WHEN char_length(NEW.body) <= 60 THEN NEW.body
              ELSE substring(NEW.body from 1 for 59) || '…'
            END;

  FOR v_recipient IN
    SELECT user_id
      FROM public.piktag_connections
     WHERE connected_user_id = v_actor
       AND user_id <> v_actor
  LOOP
    -- Block guard (per recipient). Must be inside the loop because a
    -- given author may be blocked by some recipients but not others.
    SELECT EXISTS (
      SELECT 1 FROM public.piktag_blocks
       WHERE (blocker_id = v_recipient.user_id AND blocked_id = v_actor)
          OR (blocker_id = v_actor             AND blocked_id = v_recipient.user_id)
    ) INTO v_blocked;
    IF v_blocked THEN
      CONTINUE;
    END IF;

    -- 24h dedup per recipient
    SELECT EXISTS (
      SELECT 1 FROM public.piktag_notifications
      WHERE user_id = v_recipient.user_id
        AND type    = 'ask_posted'
        AND data->>'ask_id' = NEW.id::text
        AND created_at > now() - interval '24 hours'
    ) INTO v_already_exists;

    IF v_already_exists THEN
      CONTINUE;
    END IF;

    INSERT INTO public.piktag_notifications (
      user_id, type, title, body, data, is_read, created_at
    ) VALUES (
      v_recipient.user_id,
      'ask_posted',
      '',
      v_body,
      jsonb_build_object(
        'actor_user_id', v_actor,
        'username',      v_actor_label,
        'avatar_url',    v_actor_avatar,
        'ask_id',        NEW.id,
        'ask_body',      NEW.body
      ),
      false,
      now()
    );

    -- Push (best-effort)
    BEGIN
      SELECT decrypted_secret INTO v_auth_key
        FROM vault.decrypted_secrets
       WHERE name = 'piktag_service_role_key' LIMIT 1;
      SELECT decrypted_secret INTO v_base_url
        FROM vault.decrypted_secrets
       WHERE name = 'piktag_supabase_url' LIMIT 1;
      SELECT push_token INTO v_push_token
        FROM public.piktag_profiles
       WHERE id = v_recipient.user_id LIMIT 1;

      IF v_auth_key IS NOT NULL
         AND v_push_token IS NOT NULL
         AND length(v_push_token) > 0 THEN
        PERFORM net.http_post(
          url     := 'https://exp.host/--/api/v2/push/send',
          headers := jsonb_build_object(
            'Content-Type',  'application/json',
            'Accept',        'application/json',
            'Authorization', 'Bearer ' || v_auth_key
          ),
          body := jsonb_build_object(
            'to',       v_push_token,
            'title',    v_actor_label,
            'body',     v_body,
            'data', jsonb_build_object(
              'type',          'ask_posted',
              'actor_user_id', v_actor,
              'ask_id',        NEW.id
            ),
            'sound',    'default',
            'priority', 'high'
          )
        );
      END IF;
    EXCEPTION WHEN OTHERS THEN
      RAISE WARNING 'notify_ask_posted push dispatch failed: %', SQLERRM;
    END;
  END LOOP;

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.notify_ask_posted() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.notify_ask_posted() TO postgres, service_role;

DROP TRIGGER IF EXISTS trg_notify_ask_posted ON public.piktag_asks;
CREATE TRIGGER trg_notify_ask_posted
AFTER INSERT ON public.piktag_asks
FOR EACH ROW EXECUTE FUNCTION public.notify_ask_posted();
